version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ems-docker
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c hot_standby=on
    ports:
      - "5430:5432"
    networks:
      - mynetwork

  db-replica:
    image: postgres:16
    container_name: postgres-replica
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - mynetwork
    entrypoint: >
      bash -c "
        rm -rf /var/lib/postgresql/data/* &&
        echo 'Waiting for primary to be ready...' &&
        until pg_isready -h db -U replicator -d ems-docker; do sleep 1; done &&
        echo 'Cloning data from primary...' &&
        PGPASSWORD=replicator_password pg_basebackup -h db -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R &&
        echo 'Clone complete. Starting replica...' &&
        exec docker-entrypoint.sh postgres
      "

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: always
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
    volumes:
      - azurite_data:/data
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --location /data
      --debug /data/debug.log

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ems-mybatis-liquibase:latest
    container_name: ems-mybatis-liquibase
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ems-docker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
    depends_on:
      db:
        condition: service_healthy
      db-replica:
        condition: service_started
      azurite:
        condition: service_started
    ports:
      - "8082:8082"
    networks:
      - mynetwork

volumes:
  postgres_data:
  postgres_replica_data:
  azurite_data:

networks:
  mynetwork:
    driver: bridge