server:
  port: 8082
  tomcat:
    max-http-form-post-size: 2147483647

api:
  location:
    baseUrl: https://api.opencagedata.com/geocode/v1/json
    key: 934ec857525e46cebdd892ef0df233f7

spring:
  application:
    name: ems-mybatis-liquibase
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5430/ems-docker
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStatus: false
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: Asia/Kolkata
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 0
          max-wait: -1

  cache:
    type: redis
    redis:
      time-to-live: 600000 #10 minutes
      cache-null-values: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 500MB
      max-request-size: 550MB

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  mail:
    host: smtp.gmail.com
    username: v4431365@gmail.com
    password: iponuhntztqltauh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.learning.emsmybatisliquibase.entity
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,prometheus  # Customize this as needed
        exclude: shutdown  # Exclude sensitive endpoints
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    enable:
      redis: true


logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        data:
          redis: DEBUG

maximum:
  login:
    count: 5

app:
  jwt:
    secret: 8ae2a6ebc0cd16aecb0e94e85c1eed0a1b1d8a668f65c3838b341a99197ff370
    refresh-secret: 9ae2a6ebc0cd16aecb0e94e85c1eed0a1b1d8a668f65c3838b341a99197ff371
  jwt-expiration-milliseconds: 1800000
  refresh-token-expiration-milliseconds: 3600000

default:
  send:
    email: v4431365@gmail.com

email:
  template:
    successful-onboard:
      name: colleague-successful-onboard-mail
      subject: Employee On-Boarded Successfully
      temp-password:
        name: colleague-successful-onboard-temp-password
    review:
      start:
        name: review-start
        subject: Your Quarter Review Started
        before:
          name: review-before-start
          subject: Your Quarter Review will start

resilience4j.circuitbreaker:
  instances:
    locationService:
      record-exceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException
