server:
  port: 8082
  tomcat:
    max-http-form-post-size: 2147483647

api:
  location:
    baseUrl: ${API_LOCATION_URL}
    key: ${API_LOCATION_KEY}

admin:
  uuid: 019a4b09-c44a-729a-ab56-48d21adb0f80

spring:
  application:
    name: ems-mybatis-liquibase
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStatus: false
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: Asia/Kolkata
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 500MB
      max-request-size: 550MB


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.learning.emsmybatisliquibase.entity
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,prometheus  # Customize this as needed
        exclude: shutdown  # Exclude sensitive endpoints
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

maximum:
  login:
    count: 5

app:
  jwt:
    secret: ${JWT_SECRET}
    refresh-secret: ${REFRESH_TOKEN_SECRET}
  jwt-expiration-milliseconds: 1800000
  refresh-token-expiration-milliseconds: 3600000

default:
  send:
    email: ${MAIL_USERNAME}

email:
  template:
    successful-onboard:
      name: colleague-successful-onboard-mail
      subject: Employee On-Boarded Successfully
      temp-password:
        name: colleague-successful-onboard-temp-password
    review:
      start:
        name: review-start
        subject: Your Quarter Review Started
        before:
          name: review-before-start
          subject: Your Quarter Review will start

resilience4j.circuitbreaker:
  instances:
    locationService:
      record-exceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException
